# Generated by Django 4.2.2 on 2023-06-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age_at_missing', models.PositiveIntegerField()),
                ('city_of_disappearance', models.CharField(max_length=100)),
                ('state_of_disappearance', models.CharField(max_length=100)),
                ('date_of_disappearance', models.DateField()),
            ],
        ),
    ]
