# Generated by Django 4.2.2 on 2023-06-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='race',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='state_of_disappearance',
            field=models.CharField(max_length=2),
        ),
    ]
