# Generated by Django 4.2.1 on 2023-06-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0002_missingperson_gender_missingperson_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='date_of_disappearance',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='race',
            field=models.CharField(max_length=1),
        ),
    ]
